### ISSUE TITLE
How to install it on custom Ubuntu 16.04 VPS?

### ISSUE THREAD

**Issue by navidei** [uProxy/uproxy-server#1]
As I don't see any wiki or readme file in project, I wanted to know how can I install uProxy server on my linux VPS?

**Comment by navidei** [comment]
I could run install_server.sh and install the server. How can I run it?

**Comment by sandrigo** [comment]
Hi Navidei, uProxy is not yet publicly released. Please stay tuned on uproxy.org for news when it becomes broadly available. Thanks!
